docker bug requires arguments in specific order (#22)
at least "Docker version 20.10.18, build b40c2f6" requires argument `--abort-on-container-exit` BEFORE argument `--exit-code-from` - otherwise it will complain that the container "--abort-on-container-exit was not found"

it's probably just a bug that ideally should be fixed upstream, but in the meantime, lets fix it here.

quote:
root@devad22:/home/hans/projects/easyad/hello-world-cypress/e2e# docker --version
Docker version 20.10.18, build b40c2f6
root@devad22:/home/hans/projects/easyad/hello-world-cypress/e2e# docker-compose up --exit-code-from --abort-on-container-exit cypress;
WARNING: using --exit-code-from implies --abort-on-container-exit
ERROR: No service named "--abort-on-container-exit" was found in your compose file.
ERROR: 2
root@devad22:/home/hans/projects/easyad/hello-world-cypress/e2e# docker-compose up --abort-on-container-exit --exit-code-from cypress;
Starting e2e_sentimentalyzer_1 ... done
Starting e2e_cypress_1         ... done
Attaching to e2e_sentimentalyzer_1, e2e_cypress_1
sentimentalyzer_1  | 2022/09/12 13:41:30 Listening on port 8123
^C